sudo: true

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7.0
      env:
        - DEPS=lowest
    - php: 7.0
      env:
        - DEPS=locked
    - php: 7.0
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
        - EXECUTE_TEST_COVERALLS=true
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

notifications:
  email: true

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]] ; then printf "\napc.enabled=1\napc.enable_cli=1\n" >> /home/travis/.phpenv/versions/`phpenv global`/etc/php.ini ; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]] ; then pecl config-set preferred_state beta; echo yes | pecl install apcu_bc; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]] ; then tail -n +3 /home/travis/.phpenv/versions/`phpenv global`/etc/php.ini > /home/travis/.phpenv/versions/`phpenv global`/etc/php.ini ; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]] ; then printf 'extension="apcu.so"'"\n"'extension="apc.so"'"\napc.enabled=1\napc.enable_cli=1\n" >> /home/travis/.phpenv/versions/`phpenv global`/etc/php.ini ; fi;
  - travis_retry composer self-update

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

before_script:
  - mkdir -p build/logs

script:
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then sudo -E php vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi